### ISSUE TITLE
SSLPlugin failed to compile on modern libssl ( aka Debian 9.0 )

### ISSUE THREAD

**Issue by dtouzeau** [z3APA3A/3proxy#298]
Trying to compile 0.9 devel with SSLPlugin on Debian 9.x

ssl_plugin.c: In function ‘ssl_plugin’:
ssl_plugin.c:389:17: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   pl->so->_send = ssl_send;
                 ^
ssl_plugin.c:390:17: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   pl->so->_recv = ssl_recv;
                 ^
ssl_plugin.c:391:19: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   pl->so->_sendto = ssl_sendto;
                   ^
ssl_plugin.c:392:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   pl->so->_recvfrom = ssl_recvfrom;
                     ^
gcc -fpic -g -O2 -fno-strict-aliasing -c -pthread -DWITHSPLICE -DGETHOSTBYNAME_R -D_THREAD_SAFE -D_REENTRANT -DNOODBC -DWITH_STD_MALLOC -DFD_SETSIZE=4096 -DWITH_POLL -DWITH_NETFILTER my_ssl.c
my_ssl.c: In function ‘ssl_copy_cert’:
my_ssl.c:118:37: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
  char hash_name_sha1[sizeof(src_cert->sha1_hash)*2 + 1];
                                     ^~
Makefile.inc:9 : la recette pour la cible « my_ssl.o » a échouée
make[2]: *** [my_ssl.o] Erreur 1

**Comment by z3APA3A** [comment]
0.9.2 builds OK with libssl 1.1
